language: ruby
rvm:
  - 2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install:
  - gem install jekyll
  - gem install html-proofer
script:
  - jekyll build
  - htmlproofer _site
branches:
  only:
    - gh-pages
    - asreekumar/*
