highlighter: rouge
encoding: utf-8
timezone: America/New_York
defaults:
   -
      scope:
         path: ""
         type: "posts"
      values:
         layout: "default"
         author: "Aditya Sreekumar"
   -

# Turn on github flavored markdown   
kramdown:
  input: GFM

         